### ISSUE TITLE
Peer review:

### ISSUE THREAD

**Issue by agonzalezrubiosaab1** [ylevy1/Project#2]
Peer review:

Technical issues:
1. The navigation bar should also be on the sitemap page
2. There is a sitemap link in the sitemap page that is unnecessary 
 Content suggestions:
1. I would use the images as links to the other pages
2. I would include a list of places to eat for the recommendations

**Comment by ylevy1** [comment]
Thanks Alejandra! Thats a great suggestion to add restaurants!
