### ISSUE TITLE
Peer Review - Noah Brown

### ISSUE THREAD

**Issue by noahbrown29** [ylevy1/Project#3]
Hi Yael,
Your website is really cool and it made me wish I went abroad during my time at Babson. On the home page, maybe think about centering the images on the page so there is not so much white space on the right side. To do this, I would add "align-items" and "justify-content" on the css style sheet. This will place all images horizontally so it does not look like there is an empty space on the right side of the page. Also, on the about page, I would try to add some pictures or videos of your time abroad to make that page a little more engaging. The table in the "class recommendations" tab is really great and I like how all the text is centered and clean. Additionally, you have a style in your index.html that I believe has to be on a different page. This is a super minor issue that could just be copied onto your style sheet. Other than that, your website looks really great and I appreciate your feedback on mine!

**Comment by ylevy1** [comment]
Hi Noah! Thanks so much for your recommendations! I like your idea to add pictures to that page to make it more engaging! I will take a look at the index.html issue. Thanks again!
