### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by ajosephs1** [ylevy1/Project#4]
Hi Yael,
I really like your website and I think it could be a great resource for students considering this program. The BBC inspired navigation bar works perfectly, it may be better to have the buttons spaced out more evenly across the window if you are planning on leaving the content as is. I thin I would also add the nav bar to the sitemap page. I'm sure you are going to add more style to it in the future so as long as the margins especially for the class recommendation table and more content is added I'm sure it will look great. I also think it would be cool to have the images on the homescreen as a slideshow with the captions underneath or maybe an enlargeImg() function so they can be easier to see. Great start!

**Comment by ylevy1** [comment]
Yes! I will definetly be adding more style and I like your recommendation to space out the buttons more evenly! Thanks for your feedback!
